server:
  port: 8070

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${score.datasource.url}
    driverClassName: ${score.datasource.driver}
    username: ${score.datasource.username}
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


logging:
  level: 
    org.hibernate.type: trace